### ISSUE TITLE
Support for sharding?

### ISSUE THREAD

**Issue by cpaika** [stuisme/protractor-pretty-html-reporter#3]
Hey, love the reports been using them for a project.  I'm wondering if they have support for sharding?  Seems that when sharding is enabled, the reports overwrite themselves so that the reports only contain data from the last running thread

**Comment by stuisme** [comment]
Thanks for asking, I need to do some research but it's something that would be nice to support. I'll start looking into it this week.

**Comment by stuisme** [comment]
@cpaika I have added basic support for sharding. I'm not sure the total run time is quite right yet. The README has been updated to show the new setup and configuration.

**Comment by cpaika** [comment]
@stuisme I'm fine with the run time being off as we get that through Jenkins, thanks for this!  Let me try it out now on our pipeline

**Comment by cpaika** [comment]
Me and another person at my company just tried it out, this worked great for both of us.  Thanks for getting back so fast on this.  I'll be sure to post/contribute in the future if theres any other functionality we find useful.

**Comment by ldeveber** [comment]
Yes, thank you so much! :D

**Comment by stuisme** [comment]
Thanks again for the request. 

FYI, we tested this with multiCapabilities at work today. It was developed using the shardOnSpec option. 

Thanks for verifying the update so quickly :-)
