### ISSUE TITLE
Spec duration time isn't showing. It just shows 'NaN s'

### ISSUE THREAD

**Issue by sanjum-austinmedsol** [stuisme/protractor-pretty-html-reporter#7]
For some reason the spec time is not showing in the report.

![image](https://user-images.githubusercontent.com/31208931/33315917-0f5f3f8c-d458-11e7-8593-732d75a9ddf8.png)

I checked the javascript file in the data folder, it's showing time there.

![image](https://user-images.githubusercontent.com/31208931/33316060-a3ab6fc6-d458-11e7-92c1-12208e03f33a.png)

I think the string 'secs' in the duration is causing the error since it's trying to divide a string by 1000.

**Comment by bvasilchik** [comment]
I"m having the same issue
